<a href="https://colab.research.google.com/github/Heba2627/NLP-Project/blob/main/NLP_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Dataset via. Pandas

In [18]:
import pandas as pd
import numpy as np
import regex as re

# Login using e.g. `huggingface-cli login` to access this dataset
splits = {'train': 'train.parquet', 'validation': 'validation.parquet', 'test': 'test.parquet'}
df = pd.read_parquet("hf://datasets/coastalcph/tydi_xor_rc/" + splits["train"])

In [32]:
print(df.columns)
answerable_df = df[df["answerable"] == True]
unanswerable_df = df[df["answerable"] == False]

print(len(answerable_df))
print(len(unanswerable_df))
print("% of dataset that is answerable:", len(answerable_df)/len(df)*100, "%")
print("% of dataset that is unanswerable:", len(unanswerable_df)/len(df)*100, "%")

Index(['question', 'context', 'lang', 'answerable', 'answer_start', 'answer',
       'answer_inlang', 'question_len', 'context_len'],
      dtype='object')
13962
1381
% of dataset that is answerable: 90.99915270807534 %
% of dataset that is unanswerable: 9.000847291924655 %

In [33]:
#Check for letters in all languages + Mark for arabic
word_pattern = re.compile(r"[\p{L}\p{M}]+", flags=re.UNICODE)

def n_tokens(text):
    return len(word_pattern.findall(str(text)))
def median_iqr(s):
    q1, median, q3 = np.percentile(s, [25, 50, 75])
    return pd.Series({"median": median, "Q1": q1, "Q3": q3, "IQR": q3 - q1})

df["question_len"] = df["question"].apply(n_tokens)
df["context_len"] = df["context"].apply(n_tokens)

#Approach idea: build a mini DataFrame to obtain a table like described in the project pdf.
length_stats = pd.DataFrame({"question_length": median_iqr(df["question_len"]), "context_length": median_iqr(df["context_len"])})
length_stats

        question_length  context_length
median              5.0            84.0
Q1                  4.0            56.0
Q3                  7.0           122.0
IQR                 3.0            66.0

In [37]:
#missing values
missing = df.isna().sum().to_frame("n_missing")
missing["pct_missing"] = (100 * missing["n_missing"]/len(df))
missing

#duplicates
dup_filter = df.duplicated(subset=["question", "context"], keep=False)
dup_amount = dup_filter.sum()
dup_groups = df[dup_filter].groupby(["question","context"]).ngroups
redudant_rows = df.duplicated(subset=["question", "context"], keep="first").sum()
print(dup_groups)
print(dup_amount)
print(redudant_rows)

17
34
17

# Tokenisation

In [45]:
!pip install deep_translator

Collecting deep_translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.13/dist-packages (from deep_translator) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.13/dist-packages (from deep_translator) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2026.7.22)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 1.5 MB/s eta 0:00:00
Installing collected packages: deep_translator
Successfully installed deep_translator-1.11.4

In [51]:
from transformers import AutoTokenizer
from deep_translator import GoogleTranslator
from collections import Counter, defaultdict

tok = AutoTokenizer.from_pretrained("xlm-roberta-base")

#We need to root out symbols so check for letter
has_letter = re.compile(r"\p{L}", flags=re.UNICODE)

#NOTE: We will probably need a special case for japanese since its the only
#language that doesnt have whitespace or punctuation!
def tokenize_words_xlmr(text):
    pieces = tok.tokenize(str(text))
    words, current = [], ""
    for p in pieces:
        if p.startswith("▁"):
            if current != "":
                words.append(current)
            current = p[1:]
        else:
            current += p
    if current != "":
        words.append(current)
    return [w.lower() for w in words if w != "" and has_letter.search(w)]

def translate(token, lang):
    try:
      return GoogleTranslator(source=lang, target="en").translate(token)
    except:
      return None

counters = defaultdict(Counter)
for lang, question in zip(df["lang"], df["question"]):
    counters[lang].update(tokenize_words_xlmr(question))

rows = [
    {"lang": lang, "token": token, "count": count}
    for lang, counter in counters.items()
    for token, count in counter.most_common(5)
]
top5_df = pd.DataFrame(rows)
top5_df["In English"] = [translate(token, lang) for token, lang in zip(top5_df["token"], top5_df["lang"])]
top5_df = top5_df[["lang", "token", "In English", "count"]]
top5_df

,lang,token,In English,count
0,bn,হয়,is,467
1,bn,প্রথম,the first,458
2,bn,কী,what,439
3,bn,কে,who,415
4,bn,কত,how much,392
5,ja,pygが最初に発表した曲は何,What was the first song released by pyg?,3
6,ja,オーロラ号の漂流時、オーロラ号に乗組員は何人いた?,How many people were on board the Aurora when ...,3
7,ja,カンザスシティが設立されたのはいつ,When was Kansas City founded?,3
8,ja,クロイツ群が初めて発見されたのはいつ,When was the Kreutz group first discovered?,3
9,ja,ライド,ride,2
10,ko,가장,most,527
11,ko,무엇인가?,What is it?,495
12,ko,언제,when,336
13,ko,몇,some,234
14,ko,어디인가?,Where is it?,228
15,ru,в,V,978
16,ru,сколько,How many,426
17,ru,на,on,385
18,ru,когда,When,251
19,ru,кто,Who,209
20,fi,on,there is,582
21,fi,mikä,What,328
22,fi,milloin,When,287
23,fi,vuonna,in the year,227
24,fi,kuka,Who,215
25,ar,في,in,592
26,ar,من,from,584
27,ar,متى,when,535
28,ar,ما,what,441
29,ar,هو,he,349
30,te,ఎవరు?,who,186
31,te,ఎన్ని,how many,161
32,te,ఎప్పుడు,when,151
33,te,ఏ,A,142
34,te,ఏది?,which one,117